name: prime_health_doctors
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  connectivity_plus: ^7.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  toastification: ^3.0.3
  font_awesome_flutter: ^10.10.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.1.1
  dart_jsonwebtoken: ^3.2.0
  http: ^1.5.0
  agora_rtc_engine: ^6.5.3
  agora_token_generator: ^1.0.0
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  dio: ^5.9.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/